authentication/urls.py
from django.conf.urls import url
from authentication.views import loginUser,logoutUser


urlpatterns = [
	url(r'^login/$', loginUser, name="login"),
	url(r'^logout/$', logoutUser, name="logout"),
    
]

info/urls.py
from django.conf.urls import url
from django.urls import path
from info.views import colonia, estado, municipio, colonia, colonia_cp,index


urlpatterns = [
    url(r'^home/$',index,name="index"),
	url(r'^info/api/v0/estado/$', estado.as_view(), name="estado"),
    url(r'^info/api/v0/municipio/$', municipio.as_view(), name="municipio"),
    url(r'^info/api/v0/colonia/$', colonia.as_view(), name="colonia"),
    path('info/api/v0/colonia/cp/<str:cp>/', colonia_cp.as_view(), name="colonia_cp"),
    
]

pruebabackendjr/urls.py
from django.contrib import admin
from django.urls import path
import authentication.urls
from django.conf.urls import url, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('token/', obtain_auth_token, name='api_token_auth'),
    url(r'^authentication/',include(('authentication.urls','users'),namespace='user')),
    url(r'^',include(('info.urls','info'),namespace='info')),
]

authentication/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models

# Create your models here.
class Estado(models.Model):
    d_estado = models.CharField(max_length=30)

class Municipio(models.Model):
    D_mnpio = models.CharField(max_length=30)
    estado=models.ForeignKey(Estado, on_delete=models.CASCADE)
   
class Colonia(models.Model):
    d_asenta = models.CharField(max_length=30)
    d_tipo_asenta = models.CharField(max_length=30)
    d_CP = models.CharField(max_length=5, blank=True, null=True)
    municipio=models.ForeignKey(Municipio, on_delete=models.CASCADE)

authentication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.http import HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.authtoken.views import obtain_auth_token

# Create your views here.

@csrf_exempt
def loginUser(request):
	if User.objects.filter(username='admin').count():
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				auth.login(request, user)

				return redirect('/port/')
			else:
				return redirect('/authentication/login/',status=status.HTTP_400_BAD_REQUEST)
	else:
		user = User.objects.create_user(username='admin',email='admin',password='admin')

	return render(request,'login/index.html')

def logoutUser(request):
    auth.logout(request)
    # Redirect to a success page.
    return redirect('/authentication/login/')

info/views.py
#from django.http import response
from django.shortcuts import render

from rest_framework import serializers, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from info.serializers import EstadoSerializer, MunicipioSerializer, ColoniaSerializer

from info.models import Estado, Municipio, Colonia

def index(request):
	return render(request,'index.html')

class estado(APIView):
    def get(self, request):
        try:
            estado_nombre = request.GET.get("nombre")
            if estado_nombre is None or estado_nombre=='':
                estados = Estado.objects.all().values()
                return render(request, 'estado.html', {'estados': estados})
            else:
                estados= Estado.objects.filter(d_estado=estado_nombre).values()
                #estados = EstadoSerializer(estado)
                return render(request, 'estado.html', {'estados': estados})           
        except Exception as e:
            print(e)
            return Response({}, status=status.HTTP_400_BAD_REQUEST)
    



class municipio(APIView):
    def get(self, request):
        try:
            municipio_nombre = request.GET.get("nombre")
            if municipio_nombre is None or municipio_nombre=='':
                municipios = Municipio.objects.all().values()
                return render(request, 'municipio.html')
            else:
                municipios= Municipio.objects.filter(D_mnpio=municipio_nombre).values()
                municipio= Municipio.objects.filter(D_mnpio=municipio_nombre).first()
                #estados = EstadoSerializer(estado)
                return render(request, 'municipio.html', {'municipios': municipios, 'estados': municipio.estado})           
        except Exception as e:
            print(e)
            return Response({}, status=status.HTTP_400_BAD_REQUEST)

class colonia(APIView):
    def get(self, request):
        try:
            colonia_nombre = request.GET.get("nombre")
            if colonia_nombre is None or colonia_nombre=='':
                colonias = Colonia.objects.all().values()
                return render(request, 'colonia.html')
            else:
               
                data = {}
                data['colonia'] = Colonia.objects.filter(d_asenta=colonia_nombre).values()
                data['municipio'] = Municipio.objects.all()
                return render(request, 'colonia.html', data)           
        except Exception as e:
            print(e)
            return Response({}, status=status.HTTP_400_BAD_REQUEST)

class colonia_cp(APIView):
    def get(self, request, cp):
        try:
           colonia= Colonia.objects.filter(d_CP=cp).all()
           serializers_colonia = ColoniaSerializer(colonia, many=True)
           return Response(serializers_colonia.data, status=status.HTTP_200_OK)
        except Exception as e:
            print(e)
            return Response({}, status=status.HTTP_400_BAD_REQUEST)
    

info/templates/colonia.html
<!doctype html>

    <head>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" href="">

        <title>Colonias</title>
    </head>

    <body bgcolor="">

        <font size="6" color="#df7644" face="Tahoma">

        Colonias

        </font><br><br>
        {% block content %}
        <form action="" method="get">
            <label id="nombre"></label>
            <input id="colonia_nombre" type="text" name="nombre" value= "">
            <input type="submit" value="Buscar">
        </form>        
            <div style="margin-left:20px;margin-top:20px">
                <h4>Colonias</h4>

                {% for c in colonia.all %}
                    <p>Nombre: {{c.d_asenta}}</p>
                    {% for m in c.municipio_set.all %}
                        <p>Municipio: {{m.D_mnpio}}</p>
                    
                    {% endfor %}
                       
                    <p>CP: {{c.d_CP}}</p>
                    
                {% endfor %}
            </div>
        {% endblock %}


    </body>
</html>

info/templates/estado.html
<!doctype html>

    <head>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" href="">

        <title>Estados</title>
    </head>

    <body bgcolor="">

        <font size="6" color="#df7644" face="Tahoma">

        Estados

        </font><br><br>
        {% block content %}
        <form action="" method="get">
            <label id="nombre"></label>
            <input id="estado_nombre" type="text" name="nombre" value= "">
            <input type="submit" value="Buscar">
        </form>        
            <div style="margin-left:20px;margin-top:20px">
                <h4>Estados</h4>

                {% for estados in estados.all %}
                    <p>Nombre: {{estados.d_estado}}</p>
                {% endfor %}
            </div>
        {% endblock %}


    </body>
</html>

info/templates/index.html
<!doctype html>

    <head>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" href="">

        <title>API Información de Estados, Municipios y Colonias</title>
    </head>

    <body bgcolor="">

        <font size="6" color="#df7644" face="Tahoma">

        API Información de Estados, Municipios y Colonias

        </font><br><br>

        <nav class="menu">

            <ul>

                <li><a href="/home/">

                <font size="6" color="#1f6dfd" face="Comics Sans CM">

                Inicio</font></a></li>

                <li><a href="/info/api/v0/estado/"><font size="6" color="#1f6dfd" face="Comics Sans CM">

                Estados</font></a></li>

                <li><a href="/info/api/v0/municipio/"><font size="6" color="#1f6dfd" face="Comics Sans CM">

                Municipios</font></a></li>

                <li><a href="/info/api/v0/colonia/"><font size="6" color="#1f6dfd" face="Comics Sans CM">

                Colonias</font></a></li>

            </ul>

        </nav>

    </body>
</html>

info/templates/municipio.html
<!doctype html>

    <head>

        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

        <link rel="stylesheet" href="">

        <title>Municipios</title>
    </head>

    <body bgcolor="">

        <font size="6" color="#df7644" face="Tahoma">

        Municipios

        </font><br><br>
        {% block content %}
        <form action="" method="get">
            <label id="nombre"></label>
            <input id="municipio_nombre" type="text" name="nombre" value= "">
            <input type="submit" value="Buscar">
        </form>        
            <div style="margin-left:20px;margin-top:20px">
                <h4>Municipios</h4>

                {% for municipio in municipios.all %}
                    <p>Nombre: {{municipio.D_mnpio}}</p>
                    
                    <p>Estado: {{estados.d_estado}}</p>
                    
                {% endfor %}
            </div>
        {% endblock %}


    </body>
</html>